functional:
    - Разработчики должны иметь возможность задавать вопросы в телеграм-канале #codebattle.
    - Канал должен позволять участникам получать ответы на вопросы.
    - Возможность присоединения к каналу должна быть доступна всем желающим разработчикам.

  non-functional:
    - Канал должен быть доступны 24/7.
    - Ответы на вопросы должны поступать в разумные сроки (например, в течение 24 часов).
    - Поддержка администраторов канала для модерирования дискуссий и обеспечения порядка.

  implicit:
    - Пользователи должны проявлять уважение друг к другу и соблюдать правила приличия.
    - В канале должна быть обеспечена конфиденциальность личной информации участников.
    - Участники предполагаются технически грамотными и готовыми к обсуждению вопросов, связанных с разработкой.
    - Ожидается, что участники будут предоставлять четкие и исчерпывающие вопросы для ускорения получения актуальных ответов.
    - Администраторы канала могут иметь дополнительные права по управлению участниками и контентом канала.
